### ISSUE TITLE
Feature request: support multi-language

### ISSUE THREAD

**Issue by LtnJo** [iam4x/bobarr#87]
Hi,
I think it would be nice to be able to search with the original title and also to have different version based on the language saved.

**Comment by iam4x** [comment]
Hi @LtnJo this is already supported but the UI of the settings is not done yet for selecting a language instead of typing it yourself (see #6)

Right now you can go to http://localhost:3000/settings and change the language here.

![image](https://user-images.githubusercontent.com/893837/80197250-b01c3180-861e-11ea-9c4a-2605269b2ef1.png)
